name: Call Reusable Test
run-name: >-
  ${{ github.workflow }}
  ${{ format('(input:{0}; runs-on:{1};)', inputs.my-input, inputs.runs-on) }}

on:
  workflow_dispatch:
    inputs:
      my-input:
        description: "My input"
        required: false
        type: string
        # default: '{"foo": ["bar", "baz"]}'
      runs-on:
        description: "runs-on argument"
        required: false
        type: string
        default: '["ubuntu-latest"]'

env:
  MY_INPUT: ${{ inputs.my-input }}
  RUNS_ON: ${{ inputs.runs-on }}

jobs:
  context:
    runs-on: ubuntu-latest
    env:
      GH_CONTEXT: ${{ toJSON(github) }}
      GH_INPUTS: ${{ toJSON(inputs) }}
    steps:
      - name: Print context
        id: context
        env:
          GH_RUNNER: ${{ toJSON(runner) }}
        run: |
          echo "::group::Inputs toJSON (raw block deserialized):"
          jq . <<< "${GH_INPUTS}"
          echo "::endgroup::"
          echo
          echo "---"
          echo
          echo "::group::GitHub context toJSON:"
          jq . <<< "${GH_CONTEXT}"
          echo "::endgroup::"
          echo
          echo "---"
          echo
          echo "::group::Runner context toJSON:"
          jq . <<< "${GH_RUNNER}"
          echo "::endgroup::"
          echo

  call-reusable:
    uses: ./.github/workflows/reusable.yaml
    with:
      input: ${{ inputs.my-input }}
      runs-on: ${{ inputs.runs-on }}

  inspect-reusable:
    needs: call-reusable
    runs-on: ubuntu-latest
    env:
      REUSABLE_CONTEXT: ${{ toJSON(needs) }}
    steps:
      - name: Print reusable workflow context
        run: |
          echo "::group::Reusable workflow full context toJSON:"
          echo "${{ toJSON(needs) }}" | jq . || true
          echo "::endgroup::"
          echo 
          echo "---"
          echo
          echo "::group::Reusable workflow job outputs toJSON:"
          echo "${{ toJSON(needs.call-reusable.outputs) }}" 
          echo
