name: Main PR Test
run-name: >-
  ${{ github.workflow }}
  ${{ contains(github.event.pull_reuest.title, 'break') && ' ðŸ’¥' || ''}}
  ${{ github.event.pull_request.draft == 1 && ' ðŸš§' || ''}}

on:
  pull_request:
    types: [opened, synchronize, reopened, edited, ready_for_review]
  

env:
  STRING_INPUT: ${{ github.event.pull_request.title }}
  BOOLEAN_INPUT: ${{ contains(github.event.pull_reuest.title, 'true') }}

jobs:
  context:
    runs-on: ${{ vars.DEFAULT_RUNNER || 'ubuntu-latest' }}
    env:
      GH_CONTEXT: ${{ toJSON(github) }}
    steps:
      - name: Print context
        id: context
        env:
          GH_RUNNER: ${{ toJSON(runner) }}
        run: |
          echo "::group::GitHub context toJSON:"
          jq . <<< "${GH_CONTEXT}"
          echo "::endgroup::"
          echo
          echo "---"
          echo
          echo "::group::Runner context toJSON:"
          jq . <<< "${GH_RUNNER}"
          echo "::endgroup::"
          echo
          echo "---"
          echo
          echo "::group::Steps context:"
          echo "${{ toJSON(steps) }}"
          echo "::endgroup::"
          echo

  call-reusable:
    if: ${{ !contains(github.event.pull_reuest.title, 'skipreusable') }}
    uses: ./.github/workflows/reusable.yaml
    with:
      runs-on: ${{ vars.DEFAULT_RUNNER || 'ubuntu-latest' }}
      string-input: ${{ github.event.pull_reuest.title }}
      boolean-input: ${{ contains(github.event.pull_reuest.title, 'true') }}
      break: ${{ contains(github.event.pull_reuest.title, 'break') }}
      continue-on-error: ${{ github.event.pull_request.draft == 1 }}

  inspect-reusable:
    needs: call-reusable
    if: always()
    runs-on: ${{ vars.DEFAULT_RUNNER || 'ubuntu-latest' }}
    env:
      NEEDS_CONTEXT: ${{ toJSON(needs) }}
    steps:
      - name: Print reusable workflow context
        run: |
          echo "Reusable workflow full context toJSON:"
          echo "${{ toJSON(needs.call-reusable) }}"
          echo 
